baseURL: http://example.org/
languageCode: en-us
title: North Country Escape
theme: ["github.com/theNewDynamic/gohugo-theme-ananke"]
enableEmoji: true

params:
  author: "Made with <3 by Middle+Summer Rentals"